GET http://localhost:5105/todos

###

POST http://localhost:5105/todos
Content-Type: application/json

{
    "id": 1,
    "name": "Demo",
    "DueDate": "2026-11-05",
    "IsCompleted": false
}

###

GET http://localhost:5105/todos/2

###

DELETE http://localhost:5105/todos/2

###

GET  http://localhost:5105/tasks/1